# Diese Datei konfiguriert den Analysator, der Dart-Code statisch auf Fehler, Warnungen und Lint-Regeln prüft.
#
# Die vom Analysator gefundenen Probleme werden in der Benutzeroberfläche von Dart-fähigen IDEs angezeigt
# (https://dart.dev/tools#ides-and-editors). Der Analysator kann auch über die Kommandozeile mit `flutter analyze`
# aufgerufen werden.
#
# Die folgende Zeile aktiviert eine Reihe empfohlener Lint-Regeln für Flutter-Apps, -Pakete und -Plugins, die gute
# Programmierpraktiken fördern sollen.
#
# Weitere Informationen zu dieser Datei findest du unter
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

# ZUsätzliche Lint-Regeln für Riverpod-Code
analyzer:
  plugins:
    - riverpod_lint

# Die für dieses Projekt angewendeten Lint-Regeln können im folgenden Abschnitt angepasst werden, um Regeln aus der
# oben eingebundenen Datei `package:flutter_lints/flutter.yaml` zu deaktivieren oder zusätzliche Regeln zu aktivieren.
# Eine Liste aller verfügbaren Lints und deren Dokumentation finden Sie unter https://dart.dev/lints.
#
# Anstatt eine Lint-Regel für das gesamte Projekt im folgenden Abschnitt zu deaktivieren, kann sie auch für eine
# einzelne Codezeile oder eine bestimmte Dart-Datei unterdrückt werden. Verwenden Sie dazu die Syntax
# `// ignore: name_of_lint` und `// ignore_for_file: name_of_lint` in der Zeile oder in der Datei, die den Lint erzeugt.
linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

# Konfiguration für den Dart-Formatierer (https://dart.dev/tools/dart-format).
# Dies sorgt für ein einheitliches Code-Design im gesamten Projekt.
formatter:
  # Legt die maximale Zeilenlänge fest, bevor der Formatierer versucht, den Code umzubrechen.
  # 100 Zeichen sind ein guter Kompromiss zwischen Lesbarkeit und Platznutzung auf modernen Monitoren.
  page_width: 999

  # Bestimmt, wie mit abschließenden Kommas (Trailing Commas) umgegangen wird.
  # 'preserve' bedeutet, dass manuell gesetzte Kommas beibehalten werden.
  # In Flutter hilft dies extrem dabei, die Einrückung von tief verschachtelten Widget-Bäumen zu steuern.
  trailing_commas: preserve
