// Mocks generated by Mockito 5.4.6 from annotations
// in privault/test/features/main/main_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:privault/database/database.dart' as _i2;
import 'package:privault/services/database_service.dart' as _i3;
import 'package:privault/services/session_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntryEntity_1 extends _i1.SmartFake implements _i2.EntryEntity {
  _FakeEntryEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionEntity_2 extends _i1.SmartFake
    implements _i2.PermissionEntity {
  _FakePermissionEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAttachmentEntity_3 extends _i1.SmartFake
    implements _i2.AttachmentEntity {
  _FakeAttachmentEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsEntity_4 extends _i1.SmartFake
    implements _i2.SettingsEntity {
  _FakeSettingsEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize(String? vaultName, _i5.Uint8List? masterKey) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [vaultName, masterKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Uint8List?> getSalt(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#getSalt, [vaultName]),
            returnValue: _i4.Future<_i5.Uint8List?>.value(),
          )
          as _i4.Future<_i5.Uint8List?>);

  @override
  _i4.Future<void> saveSalt(String? vaultName, _i5.Uint8List? saltBytes) =>
      (super.noSuchMethod(
            Invocation.method(#saveSalt, [vaultName, saltBytes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getDatabasePath(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, [vaultName]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getDatabasePath, [vaultName]),
            ),
          )
          as String);

  @override
  _i4.Future<bool> databaseExists(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#databaseExists, [vaultName]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getExistingVaults() =>
      (super.noSuchMethod(
            Invocation.method(#getExistingVaults, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> rekey(_i5.Uint8List? newMasterKey) =>
      (super.noSuchMethod(
            Invocation.method(#rekey, [newMasterKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeBackup() =>
      (super.noSuchMethod(
            Invocation.method(#removeBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> restoreBackup() =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> renameDatabaseAndSaltFile(
    String? oldName,
    String? newName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameDatabaseAndSaltFile, [oldName, newName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCurrentDatabaseAndSaltFile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentDatabaseAndSaltFile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.UserEntity>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i4.Future<List<_i2.UserEntity>>);

  @override
  _i4.Future<List<_i2.UserEntity>> getNotHiddenFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getNotHiddenFriends, []),
            returnValue: _i4.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i4.Future<List<_i2.UserEntity>>);

  @override
  _i4.Future<List<({int accessLevel, _i2.UserEntity user})>>
  getNotHiddenFriendsWithAccessLevel(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotHiddenFriendsWithAccessLevel, [entryId]),
            returnValue:
                _i4.Future<
                  List<({int accessLevel, _i2.UserEntity user})>
                >.value(<({int accessLevel, _i2.UserEntity user})>[]),
          )
          as _i4.Future<List<({int accessLevel, _i2.UserEntity user})>>);

  @override
  _i4.Future<_i2.UserEntity?> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<_i2.UserEntity?> getUserByUuid(String? userUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUuid, [userUuid]),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<_i2.UserEntity?> getUserByName(String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByName, [userName]),
            returnValue: _i4.Future<_i2.UserEntity?>.value(),
          )
          as _i4.Future<_i2.UserEntity?>);

  @override
  _i4.Future<bool> hasUnverifiedUser() =>
      (super.noSuchMethod(
            Invocation.method(#hasUnverifiedUser, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.UserEntity> saveUser(_i2.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i4.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#saveUser, [user])),
            ),
          )
          as _i4.Future<_i2.UserEntity>);

  @override
  _i4.Future<void> hideUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hideUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.EntryEntity>> getEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getEntries, []),
            returnValue: _i4.Future<List<_i2.EntryEntity>>.value(
              <_i2.EntryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.EntryEntity>>);

  @override
  _i4.Future<List<_i2.EntryEntity>> getEntriesSince(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesSince, [since]),
            returnValue: _i4.Future<List<_i2.EntryEntity>>.value(
              <_i2.EntryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.EntryEntity>>);

  @override
  _i4.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<_i2.EntryEntity?> getEntry(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntry, [entryId]),
            returnValue: _i4.Future<_i2.EntryEntity?>.value(),
          )
          as _i4.Future<_i2.EntryEntity?>);

  @override
  _i4.Future<_i2.EntryEntity?> getEntryByUuid(String? entryUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryByUuid, [entryUuid]),
            returnValue: _i4.Future<_i2.EntryEntity?>.value(),
          )
          as _i4.Future<_i2.EntryEntity?>);

  @override
  _i4.Future<_i2.EntryEntity> saveEntry(_i2.EntryEntity? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntry, [entry]),
            returnValue: _i4.Future<_i2.EntryEntity>.value(
              _FakeEntryEntity_1(this, Invocation.method(#saveEntry, [entry])),
            ),
          )
          as _i4.Future<_i2.EntryEntity>);

  @override
  _i4.Future<_i2.EntryEntity> saveEntryWithPermissions(
    _i2.EntryEntity? entry,
    int? userId,
    String? encryptedKey, {
    int? accessLevel = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveEntryWithPermissions,
              [entry, userId, encryptedKey],
              {#accessLevel: accessLevel},
            ),
            returnValue: _i4.Future<_i2.EntryEntity>.value(
              _FakeEntryEntity_1(
                this,
                Invocation.method(
                  #saveEntryWithPermissions,
                  [entry, userId, encryptedKey],
                  {#accessLevel: accessLevel},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.EntryEntity>);

  @override
  _i4.Future<void> deleteEntryAndForget(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntryAndForget, [entryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEntry(int? entryId, {DateTime? deletedAt}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [entryId], {#deletedAt: deletedAt}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.PermissionEntity>> getPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#getPermissions, []),
            returnValue: _i4.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PermissionEntity>>);

  @override
  _i4.Future<List<_i2.PermissionEntity>> getPermissionsByEntryId(
    int? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsByEntryId, [entryId]),
            returnValue: _i4.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PermissionEntity>>);

  @override
  _i4.Future<List<_i2.PermissionEntity>> getPermissionsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsByUserId, [userId]),
            returnValue: _i4.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PermissionEntity>>);

  @override
  _i4.Future<List<_i2.PermissionEntity>> getPermissionsWithoutKeyByUserId(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsWithoutKeyByUserId, [userId]),
            returnValue: _i4.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PermissionEntity>>);

  @override
  _i4.Future<bool> hasPermissionsWithoutKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermissionsWithoutKey, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<int>> getUserIdsWithEmptyEntryKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdsWithEmptyEntryKeys, []),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<_i2.PermissionEntity?> getPermission(int? permissionId) =>
      (super.noSuchMethod(
            Invocation.method(#getPermission, [permissionId]),
            returnValue: _i4.Future<_i2.PermissionEntity?>.value(),
          )
          as _i4.Future<_i2.PermissionEntity?>);

  @override
  _i4.Future<_i2.PermissionEntity?> getPermissionByEntryIdAndUserId(
    int? entryId,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionByEntryIdAndUserId, [
              entryId,
              userId,
            ]),
            returnValue: _i4.Future<_i2.PermissionEntity?>.value(),
          )
          as _i4.Future<_i2.PermissionEntity?>);

  @override
  _i4.Future<_i2.PermissionEntity> savePermission(
    _i2.PermissionEntity? permission,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePermission, [permission]),
            returnValue: _i4.Future<_i2.PermissionEntity>.value(
              _FakePermissionEntity_2(
                this,
                Invocation.method(#savePermission, [permission]),
              ),
            ),
          )
          as _i4.Future<_i2.PermissionEntity>);

  @override
  _i4.Future<void> updatePermissions(List<_i2.PermissionEntity>? permissions) =>
      (super.noSuchMethod(
            Invocation.method(#updatePermissions, [permissions]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePermission(int? permissionId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePermission, [permissionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeEntryKeysForUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeEntryKeysForUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.TombstoneEntity>> getTombstonesSince(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#getTombstonesSince, [since]),
            returnValue: _i4.Future<List<_i2.TombstoneEntity>>.value(
              <_i2.TombstoneEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TombstoneEntity>>);

  @override
  _i4.Future<List<_i2.AttachmentEntity>> getAttachmentsByEntryId(
    int? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsByEntryId, [entryId]),
            returnValue: _i4.Future<List<_i2.AttachmentEntity>>.value(
              <_i2.AttachmentEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AttachmentEntity>>);

  @override
  _i4.Future<List<_i2.AttachmentEntity>> getAttachmentsUnsynced() =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsUnsynced, []),
            returnValue: _i4.Future<List<_i2.AttachmentEntity>>.value(
              <_i2.AttachmentEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AttachmentEntity>>);

  @override
  _i4.Future<_i2.AttachmentEntity?> getAttachment(int? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachment, [attachmentId]),
            returnValue: _i4.Future<_i2.AttachmentEntity?>.value(),
          )
          as _i4.Future<_i2.AttachmentEntity?>);

  @override
  _i4.Future<_i2.AttachmentEntity?> getAttachmentByUuid(
    String? attachmentUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentByUuid, [attachmentUuid]),
            returnValue: _i4.Future<_i2.AttachmentEntity?>.value(),
          )
          as _i4.Future<_i2.AttachmentEntity?>);

  @override
  _i4.Future<_i2.AttachmentEntity> saveAttachment(
    _i2.AttachmentEntity? attachment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAttachment, [attachment]),
            returnValue: _i4.Future<_i2.AttachmentEntity>.value(
              _FakeAttachmentEntity_3(
                this,
                Invocation.method(#saveAttachment, [attachment]),
              ),
            ),
          )
          as _i4.Future<_i2.AttachmentEntity>);

  @override
  _i4.Future<void> deleteAttachment(int? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttachment, [attachmentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.SettingsEntity?> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i4.Future<_i2.SettingsEntity?>.value(),
          )
          as _i4.Future<_i2.SettingsEntity?>);

  @override
  _i4.Future<_i2.SettingsEntity> saveSettings(_i2.SettingsEntity? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i4.Future<_i2.SettingsEntity>.value(
              _FakeSettingsEntity_4(
                this,
                Invocation.method(#saveSettings, [settings]),
              ),
            ),
          )
          as _i4.Future<_i2.SettingsEntity>);

  @override
  _i4.Future<void> import(
    List<
      ({
        List<({String encryptedContent, String encryptedMeta, String uuid})>
        attachments,
        String encryptedEntryKey,
        _i2.EntryEntity entry,
      })
    >?
    items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#import, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i7.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get vaultName =>
      (super.noSuchMethod(
            Invocation.getter(#vaultName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#vaultName),
            ),
          )
          as String);

  @override
  void setSession({
    required _i2.UserEntity? user,
    required _i5.Uint8List? privateKey,
    required String? vaultName,
    required _i2.SettingsEntity? settings,
  }) => super.noSuchMethod(
    Invocation.method(#setSession, [], {
      #user: user,
      #privateKey: privateKey,
      #vaultName: vaultName,
      #settings: settings,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clearSession() => super.noSuchMethod(
    Invocation.method(#clearSession, []),
    returnValueForMissingStub: null,
  );

  @override
  void setUser(_i2.UserEntity? value) => super.noSuchMethod(
    Invocation.method(#setUser, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setPrivateKey(_i5.Uint8List? value) => super.noSuchMethod(
    Invocation.method(#setPrivateKey, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setVaultName(String? value) => super.noSuchMethod(
    Invocation.method(#setVaultName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSettings(_i2.SettingsEntity? value) => super.noSuchMethod(
    Invocation.method(#setSettings, [value]),
    returnValueForMissingStub: null,
  );
}
