// Mocks generated by Mockito 5.4.6 from annotations
// in famkey/test/services/database_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:famkey/core/logger.dart' as _i5;
import 'package:famkey/services/config_service.dart' as _i2;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get lastVaultName =>
      (super.noSuchMethod(
            Invocation.getter(#lastVaultName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#lastVaultName),
            ),
          )
          as String);

  @override
  bool get showOnlyMine =>
      (super.noSuchMethod(Invocation.getter(#showOnlyMine), returnValue: false)
          as bool);

  @override
  bool get categoriesCollapsed =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesCollapsed),
            returnValue: false,
          )
          as bool);

  @override
  _i4.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i4.ThemeMode.system,
          )
          as _i4.ThemeMode);

  @override
  _i5.LogLevel get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logLevel),
            returnValue: _i5.LogLevel.debug,
          )
          as _i5.LogLevel);

  @override
  int get logDays =>
      (super.noSuchMethod(Invocation.getter(#logDays), returnValue: 0) as int);

  @override
  int get logSize =>
      (super.noSuchMethod(Invocation.getter(#logSize), returnValue: 0) as int);

  @override
  int get hibpCacheDays =>
      (super.noSuchMethod(Invocation.getter(#hibpCacheDays), returnValue: 0)
          as int);

  @override
  bool get isAutotypeEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutotypeEnabled),
            returnValue: false,
          )
          as bool);

  @override
  String get autotypeHotkey =>
      (super.noSuchMethod(
            Invocation.getter(#autotypeHotkey),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#autotypeHotkey),
            ),
          )
          as String);

  @override
  set lastVaultName(String? value) => super.noSuchMethod(
    Invocation.setter(#lastVaultName, value),
    returnValueForMissingStub: null,
  );

  @override
  set showOnlyMine(bool? value) => super.noSuchMethod(
    Invocation.setter(#showOnlyMine, value),
    returnValueForMissingStub: null,
  );

  @override
  set categoriesCollapsed(bool? value) => super.noSuchMethod(
    Invocation.setter(#categoriesCollapsed, value),
    returnValueForMissingStub: null,
  );

  @override
  set themeMode(_i4.ThemeMode? value) => super.noSuchMethod(
    Invocation.setter(#themeMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set logLevel(_i5.LogLevel? value) => super.noSuchMethod(
    Invocation.setter(#logLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  set logDays(int? value) => super.noSuchMethod(
    Invocation.setter(#logDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set logSize(int? value) => super.noSuchMethod(
    Invocation.setter(#logSize, value),
    returnValueForMissingStub: null,
  );

  @override
  set hibpCacheDays(int? value) => super.noSuchMethod(
    Invocation.setter(#hibpCacheDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoLockSeconds(int? value) => super.noSuchMethod(
    Invocation.setter(#autoLockSeconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set clipboardClearSeconds(int? value) => super.noSuchMethod(
    Invocation.setter(#clipboardClearSeconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set isAutotypeEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#isAutotypeEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set autotypeHotkey(String? value) => super.noSuchMethod(
    Invocation.setter(#autotypeHotkey, value),
    returnValueForMissingStub: null,
  );
}
