// Mocks generated by Mockito 5.4.6 from annotations
// in privault/test/services/database_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:privault/core/logger.dart' as _i5;
import 'package:privault/services/config_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get lastVaultName =>
      (super.noSuchMethod(
            Invocation.getter(#lastVaultName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#lastVaultName),
            ),
          )
          as String);

  @override
  bool get showOnlyMine =>
      (super.noSuchMethod(Invocation.getter(#showOnlyMine), returnValue: false)
          as bool);

  @override
  _i4.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i4.ThemeMode.system,
          )
          as _i4.ThemeMode);

  @override
  _i5.LogLevel get logMinLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logMinLevel),
            returnValue: _i5.LogLevel.debug,
          )
          as _i5.LogLevel);

  @override
  int get logMaxDays =>
      (super.noSuchMethod(Invocation.getter(#logMaxDays), returnValue: 0)
          as int);

  @override
  int get hibpCacheDays =>
      (super.noSuchMethod(Invocation.getter(#hibpCacheDays), returnValue: 0)
          as int);

  @override
  bool get autofillEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#autofillEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get autofillRelockAfterFill =>
      (super.noSuchMethod(
            Invocation.getter(#autofillRelockAfterFill),
            returnValue: false,
          )
          as bool);

  @override
  String get autofillHotkey =>
      (super.noSuchMethod(
            Invocation.getter(#autofillHotkey),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#autofillHotkey),
            ),
          )
          as String);

  @override
  set lastVaultName(String? value) => super.noSuchMethod(
    Invocation.setter(#lastVaultName, value),
    returnValueForMissingStub: null,
  );

  @override
  set showOnlyMine(bool? value) => super.noSuchMethod(
    Invocation.setter(#showOnlyMine, value),
    returnValueForMissingStub: null,
  );

  @override
  set themeMode(_i4.ThemeMode? value) => super.noSuchMethod(
    Invocation.setter(#themeMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set logMinLevel(_i5.LogLevel? value) => super.noSuchMethod(
    Invocation.setter(#logMinLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  set logMaxDays(int? value) => super.noSuchMethod(
    Invocation.setter(#logMaxDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set hibpCacheDays(int? value) => super.noSuchMethod(
    Invocation.setter(#hibpCacheDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoLockMinutes(int? value) => super.noSuchMethod(
    Invocation.setter(#autoLockMinutes, value),
    returnValueForMissingStub: null,
  );

  @override
  set clipboardClearSeconds(int? value) => super.noSuchMethod(
    Invocation.setter(#clipboardClearSeconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set autofillEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#autofillEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set autofillRelockAfterFill(bool? value) => super.noSuchMethod(
    Invocation.setter(#autofillRelockAfterFill, value),
    returnValueForMissingStub: null,
  );

  @override
  set autofillHotkey(String? value) => super.noSuchMethod(
    Invocation.setter(#autofillHotkey, value),
    returnValueForMissingStub: null,
  );
}
