// Mocks generated by Mockito 5.4.6 from annotations
// in famkey/test/services/web_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

import 'package:famkey/services/crypto_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CryptoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoService extends _i1.Mock implements _i2.CryptoService {
  MockCryptoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Uint8List generateAesKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateAesKey, []),
            returnValue: _i3.Uint8List(0),
          )
          as _i3.Uint8List);

  @override
  _i4.Future<_i3.Uint8List> deriveKey(String? password, _i3.Uint8List? salt) =>
      (super.noSuchMethod(
            Invocation.method(#deriveKey, [password, salt]),
            returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
          )
          as _i4.Future<_i3.Uint8List>);

  @override
  _i4.Future<String> encrypt(_i3.Uint8List? data, _i3.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [data, key]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#encrypt, [data, key]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i3.Uint8List> decrypt(
    String? encryptedDataBase64,
    _i3.Uint8List? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encryptedDataBase64, key]),
            returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
          )
          as _i4.Future<_i3.Uint8List>);

  @override
  _i4.Future<(String, _i3.Uint8List)> generateRsaKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateRsaKeyPair, []),
            returnValue: _i4.Future<(String, _i3.Uint8List)>.value((
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generateRsaKeyPair, []),
              ),
              _i3.Uint8List(0),
            )),
          )
          as _i4.Future<(String, _i3.Uint8List)>);

  @override
  _i4.Future<String> encryptRsa(_i3.Uint8List? data, String? publicKeyBase64) =>
      (super.noSuchMethod(
            Invocation.method(#encryptRsa, [data, publicKeyBase64]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#encryptRsa, [data, publicKeyBase64]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i3.Uint8List> decryptRsa(
    String? encryptedDataBase64,
    _i3.Uint8List? privateKeyBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptRsa, [
              encryptedDataBase64,
              privateKeyBytes,
            ]),
            returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
          )
          as _i4.Future<_i3.Uint8List>);

  @override
  _i4.Future<String> signData(
    _i3.Uint8List? data,
    _i3.Uint8List? privateKeyBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signData, [data, privateKeyBytes]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#signData, [data, privateKeyBytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  String fingerprint(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#fingerprint, [publicKey]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#fingerprint, [publicKey]),
            ),
          )
          as String);

  @override
  _i4.Future<_i3.Uint8List> deriveKeyFromKey(
    _i3.Uint8List? keyMaterial,
    _i3.Uint8List? salt,
    String? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deriveKeyFromKey, [keyMaterial, salt, info]),
            returnValue: _i4.Future<_i3.Uint8List>.value(_i3.Uint8List(0)),
          )
          as _i4.Future<_i3.Uint8List>);

  @override
  String computeHash(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#computeHash, [input]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#computeHash, [input]),
            ),
          )
          as String);

  @override
  _i3.Uint8List generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i3.Uint8List(0),
          )
          as _i3.Uint8List);

  @override
  void wipeKey(_i3.Uint8List? key) => super.noSuchMethod(
    Invocation.method(#wipeKey, [key]),
    returnValueForMissingStub: null,
  );
}
