SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `tombstones`;
DROP TABLE IF EXISTS `attachments`;
DROP TABLE IF EXISTS `permissions`;
DROP TABLE IF EXISTS `entries`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `vaults`;
DROP TABLE IF EXISTS `version`;
SET FOREIGN_KEY_CHECKS = 1;