// Mocks generated by Mockito 5.4.6 from annotations
// in FamKey/test/features/main/sync/sync_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i7;

import 'package:flutter/material.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:famkey/core/logger.dart' as _i15;
import 'package:famkey/database/database.dart' as _i2;
import 'package:famkey/models/dtos/sync_dtos.dart' as _i5;
import 'package:famkey/models/dtos/user_response.dart' as _i4;
import 'package:famkey/models/dtos/version_response.dart' as _i3;
import 'package:famkey/services/config_service.dart' as _i13;
import 'package:famkey/services/crypto_service.dart' as _i6;
import 'package:famkey/services/database_service.dart' as _i10;
import 'package:famkey/services/session_service.dart' as _i11;
import 'package:famkey/services/web_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntryEntity_1 extends _i1.SmartFake implements _i2.EntryEntity {
  _FakeEntryEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePermissionEntity_2 extends _i1.SmartFake
    implements _i2.PermissionEntity {
  _FakePermissionEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAttachmentEntity_3 extends _i1.SmartFake
    implements _i2.AttachmentEntity {
  _FakeAttachmentEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsEntity_4 extends _i1.SmartFake
    implements _i2.SettingsEntity {
  _FakeSettingsEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVersionResponse_5 extends _i1.SmartFake
    implements _i3.VersionResponse {
  _FakeVersionResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_6 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncPullResponse_7 extends _i1.SmartFake
    implements _i5.SyncPullResponse {
  _FakeSyncPullResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CryptoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoService extends _i1.Mock implements _i6.CryptoService {
  MockCryptoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Uint8List generateAesKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateAesKey, []),
            returnValue: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  _i8.Future<_i7.Uint8List> deriveKey(String? password, _i7.Uint8List? salt) =>
      (super.noSuchMethod(
            Invocation.method(#deriveKey, [password, salt]),
            returnValue: _i8.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i8.Future<_i7.Uint8List>);

  @override
  _i8.Future<String> encrypt(_i7.Uint8List? data, _i7.Uint8List? key) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [data, key]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#encrypt, [data, key]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i7.Uint8List> decrypt(
    String? encryptedDataBase64,
    _i7.Uint8List? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encryptedDataBase64, key]),
            returnValue: _i8.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i8.Future<_i7.Uint8List>);

  @override
  _i8.Future<(String, _i7.Uint8List)> generateRsaKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateRsaKeyPair, []),
            returnValue: _i8.Future<(String, _i7.Uint8List)>.value((
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateRsaKeyPair, []),
              ),
              _i7.Uint8List(0),
            )),
          )
          as _i8.Future<(String, _i7.Uint8List)>);

  @override
  _i8.Future<String> encryptRsa(_i7.Uint8List? data, String? publicKeyBase64) =>
      (super.noSuchMethod(
            Invocation.method(#encryptRsa, [data, publicKeyBase64]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#encryptRsa, [data, publicKeyBase64]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i7.Uint8List> decryptRsa(
    String? encryptedDataBase64,
    _i7.Uint8List? privateKeyBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptRsa, [
              encryptedDataBase64,
              privateKeyBytes,
            ]),
            returnValue: _i8.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i8.Future<_i7.Uint8List>);

  @override
  _i8.Future<String> signData(
    _i7.Uint8List? data,
    _i7.Uint8List? privateKeyBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signData, [data, privateKeyBytes]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#signData, [data, privateKeyBytes]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String fingerprint(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#fingerprint, [publicKey]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#fingerprint, [publicKey]),
            ),
          )
          as String);

  @override
  _i8.Future<_i7.Uint8List> deriveKeyFromKey(
    _i7.Uint8List? keyMaterial,
    _i7.Uint8List? salt,
    String? info,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deriveKeyFromKey, [keyMaterial, salt, info]),
            returnValue: _i8.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i8.Future<_i7.Uint8List>);

  @override
  String computeHash(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#computeHash, [input]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#computeHash, [input]),
            ),
          )
          as String);

  @override
  _i7.Uint8List generateSalt() =>
      (super.noSuchMethod(
            Invocation.method(#generateSalt, []),
            returnValue: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  void wipeKey(_i7.Uint8List? key) => super.noSuchMethod(
    Invocation.method(#wipeKey, [key]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i10.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i8.Future<void> initialize(String? vaultName, _i7.Uint8List? masterKey) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [vaultName, masterKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i7.Uint8List?> getSalt(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#getSalt, [vaultName]),
            returnValue: _i8.Future<_i7.Uint8List?>.value(),
          )
          as _i8.Future<_i7.Uint8List?>);

  @override
  _i8.Future<void> saveSalt(String? vaultName, _i7.Uint8List? saltBytes) =>
      (super.noSuchMethod(
            Invocation.method(#saveSalt, [vaultName, saltBytes]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String getDatabasePath(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, [vaultName]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getDatabasePath, [vaultName]),
            ),
          )
          as String);

  @override
  _i8.Future<bool> databaseExists(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#databaseExists, [vaultName]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<String>> getExistingVaults() =>
      (super.noSuchMethod(
            Invocation.method(#getExistingVaults, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> rekey(_i7.Uint8List? newMasterKey) =>
      (super.noSuchMethod(
            Invocation.method(#rekey, [newMasterKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> createBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createBackup, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeBackup() =>
      (super.noSuchMethod(
            Invocation.method(#removeBackup, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> restoreBackup() =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackup, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> renameDatabaseAndSaltFile(
    String? oldName,
    String? newName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameDatabaseAndSaltFile, [oldName, newName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCurrentDatabaseAndSaltFile() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrentDatabaseAndSaltFile, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.UserEntity>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i8.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i8.Future<List<_i2.UserEntity>>);

  @override
  _i8.Future<List<_i2.UserEntity>> getNotHiddenFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getNotHiddenFriends, []),
            returnValue: _i8.Future<List<_i2.UserEntity>>.value(
              <_i2.UserEntity>[],
            ),
          )
          as _i8.Future<List<_i2.UserEntity>>);

  @override
  _i8.Future<bool> hasFriends() =>
      (super.noSuchMethod(
            Invocation.method(#hasFriends, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<({int accessLevel, _i2.UserEntity user})>>
  getNotHiddenFriendsWithAccessLevel(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotHiddenFriendsWithAccessLevel, [entryId]),
            returnValue:
                _i8.Future<
                  List<({int accessLevel, _i2.UserEntity user})>
                >.value(<({int accessLevel, _i2.UserEntity user})>[]),
          )
          as _i8.Future<List<({int accessLevel, _i2.UserEntity user})>>);

  @override
  _i8.Future<_i2.UserEntity?> getUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i8.Future<_i2.UserEntity?>.value(),
          )
          as _i8.Future<_i2.UserEntity?>);

  @override
  _i8.Future<_i2.UserEntity?> getUserByUuid(String? userUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUuid, [userUuid]),
            returnValue: _i8.Future<_i2.UserEntity?>.value(),
          )
          as _i8.Future<_i2.UserEntity?>);

  @override
  _i8.Future<_i2.UserEntity?> getUserByName(String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByName, [userName]),
            returnValue: _i8.Future<_i2.UserEntity?>.value(),
          )
          as _i8.Future<_i2.UserEntity?>);

  @override
  _i8.Future<bool> hasUnverifiedUser() =>
      (super.noSuchMethod(
            Invocation.method(#hasUnverifiedUser, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.UserEntity> saveUser(_i2.UserEntity? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i8.Future<_i2.UserEntity>.value(
              _FakeUserEntity_0(this, Invocation.method(#saveUser, [user])),
            ),
          )
          as _i8.Future<_i2.UserEntity>);

  @override
  _i8.Future<void> hideUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hideUser, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.EntryEntity>> getEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getEntries, []),
            returnValue: _i8.Future<List<_i2.EntryEntity>>.value(
              <_i2.EntryEntity>[],
            ),
          )
          as _i8.Future<List<_i2.EntryEntity>>);

  @override
  _i8.Future<List<_i2.EntryEntity>> getEntriesSince(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesSince, [since]),
            returnValue: _i8.Future<List<_i2.EntryEntity>>.value(
              <_i2.EntryEntity>[],
            ),
          )
          as _i8.Future<List<_i2.EntryEntity>>);

  @override
  _i8.Future<_i2.EntryEntity?> getEntry(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntry, [entryId]),
            returnValue: _i8.Future<_i2.EntryEntity?>.value(),
          )
          as _i8.Future<_i2.EntryEntity?>);

  @override
  _i8.Future<_i2.EntryEntity?> getEntryByUuid(String? entryUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryByUuid, [entryUuid]),
            returnValue: _i8.Future<_i2.EntryEntity?>.value(),
          )
          as _i8.Future<_i2.EntryEntity?>);

  @override
  _i8.Future<_i2.EntryEntity> saveEntry(_i2.EntryEntity? entry) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntry, [entry]),
            returnValue: _i8.Future<_i2.EntryEntity>.value(
              _FakeEntryEntity_1(this, Invocation.method(#saveEntry, [entry])),
            ),
          )
          as _i8.Future<_i2.EntryEntity>);

  @override
  _i8.Future<_i2.EntryEntity> saveEntryWithPermissions(
    _i2.EntryEntity? entry,
    int? userId,
    String? encryptedKey, {
    int? accessLevel = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveEntryWithPermissions,
              [entry, userId, encryptedKey],
              {#accessLevel: accessLevel},
            ),
            returnValue: _i8.Future<_i2.EntryEntity>.value(
              _FakeEntryEntity_1(
                this,
                Invocation.method(
                  #saveEntryWithPermissions,
                  [entry, userId, encryptedKey],
                  {#accessLevel: accessLevel},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.EntryEntity>);

  @override
  _i8.Future<void> deleteEntryAndForget(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntryAndForget, [entryId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteEntry(int? entryId, {DateTime? deletedAt}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [entryId], {#deletedAt: deletedAt}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.PermissionEntity>> getPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#getPermissions, []),
            returnValue: _i8.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i8.Future<List<_i2.PermissionEntity>>);

  @override
  _i8.Future<List<_i2.PermissionEntity>> getPermissionsByEntryId(
    int? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsByEntryId, [entryId]),
            returnValue: _i8.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i8.Future<List<_i2.PermissionEntity>>);

  @override
  _i8.Future<List<_i2.PermissionEntity>> getPermissionsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsByUserId, [userId]),
            returnValue: _i8.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i8.Future<List<_i2.PermissionEntity>>);

  @override
  _i8.Future<List<_i2.PermissionEntity>> getPermissionsWithoutKeyByUserId(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionsWithoutKeyByUserId, [userId]),
            returnValue: _i8.Future<List<_i2.PermissionEntity>>.value(
              <_i2.PermissionEntity>[],
            ),
          )
          as _i8.Future<List<_i2.PermissionEntity>>);

  @override
  _i8.Future<bool> hasPermissionsWithoutKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermissionsWithoutKey, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<int>> getUserIdsWithEmptyEntryKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdsWithEmptyEntryKeys, []),
            returnValue: _i8.Future<List<int>>.value(<int>[]),
          )
          as _i8.Future<List<int>>);

  @override
  _i8.Future<_i2.PermissionEntity?> getPermission(int? permissionId) =>
      (super.noSuchMethod(
            Invocation.method(#getPermission, [permissionId]),
            returnValue: _i8.Future<_i2.PermissionEntity?>.value(),
          )
          as _i8.Future<_i2.PermissionEntity?>);

  @override
  _i8.Future<_i2.PermissionEntity?> getPermissionByEntryIdAndUserId(
    int? entryId,
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPermissionByEntryIdAndUserId, [
              entryId,
              userId,
            ]),
            returnValue: _i8.Future<_i2.PermissionEntity?>.value(),
          )
          as _i8.Future<_i2.PermissionEntity?>);

  @override
  _i8.Future<_i2.PermissionEntity> savePermission(
    _i2.PermissionEntity? permission,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePermission, [permission]),
            returnValue: _i8.Future<_i2.PermissionEntity>.value(
              _FakePermissionEntity_2(
                this,
                Invocation.method(#savePermission, [permission]),
              ),
            ),
          )
          as _i8.Future<_i2.PermissionEntity>);

  @override
  _i8.Future<void> updatePermissions(List<_i2.PermissionEntity>? permissions) =>
      (super.noSuchMethod(
            Invocation.method(#updatePermissions, [permissions]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deletePermission(int? permissionId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePermission, [permissionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeEntryKeysForUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeEntryKeysForUser, [userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.TombstoneEntity>> getTombstonesSince(DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#getTombstonesSince, [since]),
            returnValue: _i8.Future<List<_i2.TombstoneEntity>>.value(
              <_i2.TombstoneEntity>[],
            ),
          )
          as _i8.Future<List<_i2.TombstoneEntity>>);

  @override
  _i8.Future<List<_i2.AttachmentEntity>> getAttachmentsByEntryId(
    int? entryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsByEntryId, [entryId]),
            returnValue: _i8.Future<List<_i2.AttachmentEntity>>.value(
              <_i2.AttachmentEntity>[],
            ),
          )
          as _i8.Future<List<_i2.AttachmentEntity>>);

  @override
  _i8.Future<List<_i2.AttachmentEntity>> getAttachmentsUnsynced() =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsUnsynced, []),
            returnValue: _i8.Future<List<_i2.AttachmentEntity>>.value(
              <_i2.AttachmentEntity>[],
            ),
          )
          as _i8.Future<List<_i2.AttachmentEntity>>);

  @override
  _i8.Future<_i2.AttachmentEntity?> getAttachment(int? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachment, [attachmentId]),
            returnValue: _i8.Future<_i2.AttachmentEntity?>.value(),
          )
          as _i8.Future<_i2.AttachmentEntity?>);

  @override
  _i8.Future<_i2.AttachmentEntity?> getAttachmentByUuid(
    String? attachmentUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentByUuid, [attachmentUuid]),
            returnValue: _i8.Future<_i2.AttachmentEntity?>.value(),
          )
          as _i8.Future<_i2.AttachmentEntity?>);

  @override
  _i8.Future<_i2.AttachmentEntity> saveAttachment(
    _i2.AttachmentEntity? attachment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAttachment, [attachment]),
            returnValue: _i8.Future<_i2.AttachmentEntity>.value(
              _FakeAttachmentEntity_3(
                this,
                Invocation.method(#saveAttachment, [attachment]),
              ),
            ),
          )
          as _i8.Future<_i2.AttachmentEntity>);

  @override
  _i8.Future<void> deleteAttachment(int? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttachment, [attachmentId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.SettingsEntity?> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i8.Future<_i2.SettingsEntity?>.value(),
          )
          as _i8.Future<_i2.SettingsEntity?>);

  @override
  _i8.Future<_i2.SettingsEntity> saveSettings(_i2.SettingsEntity? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i8.Future<_i2.SettingsEntity>.value(
              _FakeSettingsEntity_4(
                this,
                Invocation.method(#saveSettings, [settings]),
              ),
            ),
          )
          as _i8.Future<_i2.SettingsEntity>);

  @override
  _i8.Future<void> import(
    List<
      ({
        List<({String encryptedContent, String encryptedMeta, String uuid})>
        attachments,
        String encryptedEntryKey,
        _i2.EntryEntity entry,
        List<({int accessLevel, String encryptedKey, int userId})>
        friendPermissions,
      })
    >?
    items,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#import, [items]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i11.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get vaultName =>
      (super.noSuchMethod(
            Invocation.getter(#vaultName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#vaultName),
            ),
          )
          as String);

  @override
  _i8.Future<void> setSession({
    required _i2.UserEntity? user,
    required _i7.Uint8List? privateKey,
    required String? vaultName,
    required _i2.SettingsEntity? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [], {
              #user: user,
              #privateKey: privateKey,
              #vaultName: vaultName,
              #settings: settings,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearSession() => super.noSuchMethod(
    Invocation.method(#clearSession, []),
    returnValueForMissingStub: null,
  );

  @override
  void setUser(_i2.UserEntity? value) => super.noSuchMethod(
    Invocation.method(#setUser, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setPrivateKey(_i7.Uint8List? value) =>
      (super.noSuchMethod(
            Invocation.method(#setPrivateKey, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void setVaultName(String? value) => super.noSuchMethod(
    Invocation.method(#setVaultName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSettings(_i2.SettingsEntity? value) => super.noSuchMethod(
    Invocation.method(#setSettings, [value]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebService extends _i1.Mock implements _i12.WebService {
  MockWebService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void updateConfig({required String? host, required String? apiToken}) =>
      super.noSuchMethod(
        Invocation.method(#updateConfig, [], {
          #host: host,
          #apiToken: apiToken,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void setSignatureData({
    required String? userUuid,
    required _i7.Uint8List? privateKey,
    String? publicKey,
  }) => super.noSuchMethod(
    Invocation.method(#setSignatureData, [], {
      #userUuid: userUuid,
      #privateKey: privateKey,
      #publicKey: publicKey,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clearSignatureData() => super.noSuchMethod(
    Invocation.method(#clearSignatureData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i3.VersionResponse> getServerVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getServerVersion, []),
            returnValue: _i8.Future<_i3.VersionResponse>.value(
              _FakeVersionResponse_5(
                this,
                Invocation.method(#getServerVersion, []),
              ),
            ),
          )
          as _i8.Future<_i3.VersionResponse>);

  @override
  _i8.Future<_i4.UserResponse?> findUser(String? vaultName, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#findUser, [vaultName, userName]),
            returnValue: _i8.Future<_i4.UserResponse?>.value(),
          )
          as _i8.Future<_i4.UserResponse?>);

  @override
  _i8.Future<_i4.UserResponse> registerUser({
    required String? vaultName,
    required String? userName,
    required String? userUuid,
    required String? salt,
    required String? publicKey,
    required String? encryptedPrivateKey,
    required DateTime? masterKeyTimestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #vaultName: vaultName,
              #userName: userName,
              #userUuid: userUuid,
              #salt: salt,
              #publicKey: publicKey,
              #encryptedPrivateKey: encryptedPrivateKey,
              #masterKeyTimestamp: masterKeyTimestamp,
            }),
            returnValue: _i8.Future<_i4.UserResponse>.value(
              _FakeUserResponse_6(
                this,
                Invocation.method(#registerUser, [], {
                  #vaultName: vaultName,
                  #userName: userName,
                  #userUuid: userUuid,
                  #salt: salt,
                  #publicKey: publicKey,
                  #encryptedPrivateKey: encryptedPrivateKey,
                  #masterKeyTimestamp: masterKeyTimestamp,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.UserResponse>);

  @override
  _i8.Future<void> changePassword(
    String? userUuid,
    String? salt,
    String? publicKey,
    String? encryptedPrivateKey,
    DateTime? masterKeyTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [
              userUuid,
              salt,
              publicKey,
              encryptedPrivateKey,
              masterKeyTimestamp,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getPublicKeys(String? userUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKeys, [userUuid]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> saveFriends(String? userUuid, String? encryptedFriends) =>
      (super.noSuchMethod(
            Invocation.method(#saveFriends, [userUuid, encryptedFriends]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> patchUserName(String? userUuid, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#patchUserName, [userUuid, userName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.SyncPullResponse> pullSync(
    String? userUuid,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pullSync, [userUuid, since]),
            returnValue: _i8.Future<_i5.SyncPullResponse>.value(
              _FakeSyncPullResponse_7(
                this,
                Invocation.method(#pullSync, [userUuid, since]),
              ),
            ),
          )
          as _i8.Future<_i5.SyncPullResponse>);

  @override
  _i8.Future<void> pushSync(String? userUuid, _i5.SyncPushRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#pushSync, [userUuid, request]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> downloadAttachment(String? attachmentUuid) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAttachment, [attachmentUuid]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> uploadAttachment(
    String? entryUuid,
    String? attachmentUuid,
    String? encryptedMeta,
    String? encryptedContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAttachment, [
              entryUuid,
              attachmentUuid,
              encryptedMeta,
              encryptedContent,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> cleanTest(String? vaultName) =>
      (super.noSuchMethod(
            Invocation.method(#cleanTest, [vaultName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteVault(String? userUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteVault, [userUuid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i13.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get lastVaultName =>
      (super.noSuchMethod(
            Invocation.getter(#lastVaultName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#lastVaultName),
            ),
          )
          as String);

  @override
  bool get showOnlyMine =>
      (super.noSuchMethod(Invocation.getter(#showOnlyMine), returnValue: false)
          as bool);

  @override
  _i14.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i14.ThemeMode.system,
          )
          as _i14.ThemeMode);

  @override
  _i15.LogLevel get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logMinLevel),
            returnValue: _i15.LogLevel.debug,
          )
          as _i15.LogLevel);

  @override
  int get logDays =>
      (super.noSuchMethod(Invocation.getter(#logMaxDays), returnValue: 0)
          as int);

  @override
  int get hibpCacheDays =>
      (super.noSuchMethod(Invocation.getter(#hibpCacheDays), returnValue: 0)
          as int);

  @override
  bool get autofillEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#autofillEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get autofillRelockAfterFill =>
      (super.noSuchMethod(
            Invocation.getter(#autofillRelockAfterFill),
            returnValue: false,
          )
          as bool);

  @override
  String get autotypeHotkey =>
      (super.noSuchMethod(
            Invocation.getter(#autofillHotkey),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#autofillHotkey),
            ),
          )
          as String);

  @override
  set lastVaultName(String? value) => super.noSuchMethod(
    Invocation.setter(#lastVaultName, value),
    returnValueForMissingStub: null,
  );

  @override
  set showOnlyMine(bool? value) => super.noSuchMethod(
    Invocation.setter(#showOnlyMine, value),
    returnValueForMissingStub: null,
  );

  @override
  set themeMode(_i14.ThemeMode? value) => super.noSuchMethod(
    Invocation.setter(#themeMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set logLevel(_i15.LogLevel? value) => super.noSuchMethod(
    Invocation.setter(#logMinLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  set logDays(int? value) => super.noSuchMethod(
    Invocation.setter(#logMaxDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set hibpCacheDays(int? value) => super.noSuchMethod(
    Invocation.setter(#hibpCacheDays, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoLockSeconds(int? value) => super.noSuchMethod(
    Invocation.setter(#autoLockSeconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set clipboardClearSeconds(int? value) => super.noSuchMethod(
    Invocation.setter(#clipboardClearSeconds, value),
    returnValueForMissingStub: null,
  );

  @override
  set autofillEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#autofillEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set autofillRelockAfterFill(bool? value) => super.noSuchMethod(
    Invocation.setter(#autofillRelockAfterFill, value),
    returnValueForMissingStub: null,
  );

  @override
  set autotypeHotkey(String? value) => super.noSuchMethod(
    Invocation.setter(#autofillHotkey, value),
    returnValueForMissingStub: null,
  );
}
